### PR TITLE
Protecting deletion of namespaces

### PR DESCRIPTION
**Pull request by lzecca78**
With this constraint is possible now to avoid accidental (or not) namespace deletion when the namespace doesn't have a specific label

### CODE REVIEW

**Review by ralgozino — APPROVED** [review]
lgtm! 🎉

**Comment by angelbarrera92** [comment]
Is it still in WIP?

**Comment by ralgozino** [comment]
yes, we need to check what happens with the older rules after enabling the DELETE operations, they might need to be modified

**Comment by angelbarrera92** [comment]
Is it still in WIP?

**Comment by lzecca78** [comment]
I am working on it, as soon as I have something working I will remove the WIP

**Comment by lzecca78** [comment]
I confirm what @ralgozino said, and I confirm that by making the changes he suggested ( in all the N-1 rules) the problem disappears. 
I've pushed everything, still some changes for the linter, but now everything seems ok!

**Comment by lzecca78** [comment]
as we opened 2 different pr (#35 , #36) i am closing this one

**Pull request closed without merging**
