### PR TITLE
feat(gatekeeper): exempt infra namespaces by default

### PR DESCRIPTION
**Pull request by ralgozino**
This PR tries to address a better default exemption for infrastructure namespaces.

Please notice that the exemption is not complete. Because of how [Gatekeeper implements namespace exemptions](https://open-policy-agent.github.io/gatekeeper/website/docs/exempt-namespaces/), you need also to add a label to the namespaces to complete the setup.

I could not think of a way of doing this automatically when the module is installed.

I'm doubtful of including this change, not only does one need to do manual operations after deploying the module to complete the exemption, this doesn't completely solve the issue of Gatekeeper "breaking" a cluster when is in Fail mode and not responding. [As the docs say](https://open-policy-agent.github.io/gatekeeper/website/docs/failing-closed/), nothing will, by design.

Maybe we could just leave the additional info in the readme if one needs to do some exemptions.

### CODE REVIEW

**Comment by lnovara** [comment]
Is this ready for review?

**Comment by ralgozino** [comment]
> Is this ready for review?

Yes, sorry 🙏

**Comment by ralgozino** [comment]
> I wonder if we should add the labels you mention by default on all the ignored namespaces so that when you deploy the module you get the expected behavior. What do you think?

We could in the namespaces that we create with the modules, like `monitoring`. But in the namespaces that are from Kubernetes itself like `kube-system` do you see a way of doing it automatically (i.e. not with `kubectl label ns <ns>`)?

I don't know if this is clear from the description & the content in the docs: this does not solve the issue of Gatekeeper misbehaving when in `Fail` mode, there are resources that are _not-namespaced_ for example that are still affected by the webhook.

**Comment by lnovara** [comment]
For the namespaces that we don't own, can't we provide manifests of such namespaces with the label set? `kubectl apply` should behave correctly and update the resource in place.

**Comment by ralgozino** [comment]
unfortunately, it is not that straightforward:

1. If we include the namespace definition in Gatekeeper's base, but you have 1 main kustomization wrapping more than 1 module (like we usually do), for example: a "root" kustomization that uses gatekeeper and monitoring bases: `kustomize` will complain that you are defining the namespace in 2 places.
2. If we use a strategic patch instead in gatekeeper kustomize for the namespaces of the other modules: you can't apply the module independently of the other because the patch will fail when it doesn't find the namespace definition to patch, for example let's say that you don't want to install monitoring or that you want to apply just the gatekeeper stuff.
3. Kubernetes' namespaces still need manual intervention :(

**Comment by lnovara** [comment]
My idea was to just include `kube-system`, `kube-public`, `kube-node-lease` and `default` with the labels in this module. Those namespaces usually are not defined in an existing Kustomize base so the risk of clashes is minimal.

**Comment by ralgozino** [comment]
> My idea was to just include `kube-system`, `kube-public`, `kube-node-lease` and `default` with the labels in this module. Those namespaces usually are not defined in an existing Kustomize base so the risk of clashes is minimal.

Unless I'm missing something, this doesn't work. You get the usual error when you try to `apply` to a resource that has been created instead of applied the first time.
For example:

```log
Warning: resource namespaces/kube-system is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
namespace/kube-system configured
```

**Comment by lnovara** [comment]
You're right, but it's should be "just" a warning and the label is ultimately added.

Out of curiosity, can you try doing the apply with the `--server-side` option? Do you still get the warning?

Thank you.

**Comment by ralgozino** [comment]
You are correct, it's a warning but the label gets applied.

Using `--server-side` doesn't trigger the warning.

**Comment by ralgozino** [comment]
I've pushed an update including the patching of Kubernetes' default namespaces: `kube-system`, `kube-node-lease` and `kube-public`.

I've left the `default` namespace out of the exemption on purpose because I think that is the only one where it could make sense to enforce policies, is where the workload can end up if you don't create a dedicated namespace.

Here's a test:

```bash
$ kubectl run --image curlimages/curl curlaiolo -- sleep 500        
Error from server (Forbidden): admission webhook "validation.gatekeeper.sh" denied the request: [liveness-probe] Rejecting "Pod/curlaiolo" for not specifying a livenessProbe
[readiness-probe] Rejecting "Pod/curlaiolo" for not specifying a readinessProbe
[enforce-deployment-and-pod-security-controls] container 'curlaiolo' in the 'curlaiolo' Pod allows priviledge escalation
[enforce-deployment-and-pod-security-controls] container 'curlaiolo' in the 'curlaiolo' Pod does not have a CPU limit set
[enforce-deployment-and-pod-security-controls] container 'curlaiolo' in the 'curlaiolo' Pod does not have a memory limit set
[enforce-deployment-and-pod-security-controls] container 'curlaiolo' in the 'curlaiolo' Pod is running as root
[enforce-deployment-and-pod-security-controls] container 'curlaiolo' in the Pod 'curlaiolo' has an image 'curlimages/curl' using the latest tag

$ kubectl run --image curlimages/curl curlaiolo --namespace kube-system -- sleep 500
pod/curlaiolo created
```

**Comment by ralgozino** [comment]
I was wondering if "forcing" the labelling of the namespaces like this could cause any issues, for example, let's say that you or some application have applied some labels to `kube-system`, kubectl-applying this module -installing or updating- will reset the labels to the ones defined here and you will lose your labels. Right?

Do we want that?

**Comment by ralgozino** [comment]
Analyze using the included label with the namespace name for the exemptions at Webhook namespace selector level.

Being that this approach won't solve the underlying issue, we decided to leave this PR for future reference and revisit it later, I will open another one with an update to the docs and explaining how exemptions work in Gatekeeper.

**Pull request closed without merging**
